function WealthManager(){var O='bootstrap',P='begin',Q='gwt.codesvr.WealthManager=',R='gwt.codesvr=',S='WealthManager',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='WealthManager::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='WealthManager.nocache.js',Ib='base',Jb='//',Kb='history.pushStateSupported',Lb='function',Mb='yes',Nb='no',Ob='user.agent',Pb='webkit',Qb='safari',Rb='msie',Sb=10,Tb=11,Ub='ie10',Vb=9,Wb='ie9',Xb=8,Yb='ie8',Zb='gecko',$b='gecko1_8',_b=2,ac=3,bc=4,cc='selectingPermutation',dc='WealthManager.devmode.js',ec='03A71F6BDD68CA816693EB222B5D8445',fc='046179814702A8D9DAEF81D7069B7F69',gc='10D3A5916E408F122C4A8B6C117DC85B',hc='52661F7910CE6163A26A1AA27F0BFBED',ic='5A22F2622D79755E5A6C91ADA1372A45',jc='6130806F3D9C4890556C573A28732437',kc='8C6B943419945BEEB2C1155508D3C44F',lc='BF383D265B8179801D955CC1EFCD029F',mc='E69667B2C5D24DFF5F0CF3AA2EEA82EB',nc=':',oc='.cache.js',pc='link',qc='rel',rc='stylesheet',sc='href',tc='loadExternalRefs',uc='gwt/standard/standard.css',vc='end',wc='http:',xc='file:',yc='_gwt_dummy_',zc='__gwtDevModeHook:WealthManager',Ac='Ignoring non-whitelisted Dev Mode URL: ',Bc=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
WealthManager.__sendStats=r;WealthManager.__moduleName=S;WealthManager.__errFn=null;WealthManager.__moduleBase=U;WealthManager.__softPermutationId=V;WealthManager.__computePropValue=null;WealthManager.__getPropMap=null;WealthManager.__installRunAsyncCode=function(){};WealthManager.__gwtStartLoadingFragment=function(){return null};WealthManager.__gwt_isKnownPropertyValue=function(){return false};WealthManager.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};WealthManager.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[WealthManager.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
WealthManager.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(WealthManager.__errFn){n.onerror=function(){WealthManager.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
WealthManager.__startLoadingFragment=function(a){return D(a)};WealthManager.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;WealthManager.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return WealthManager.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){if(typeof window.history.pushState==Lb){return Mb}else{return Nb}};i[Kb]={no:V,yes:W};j[Ob]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(Pb)!=-1}())return Qb;if(function(){return a.indexOf(Rb)!=-1&&(b>=Sb&&b<Tb)}())return Ub;if(function(){return a.indexOf(Rb)!=-1&&(b>=Vb&&b<Tb)}())return Wb;if(function(){return a.indexOf(Rb)!=-1&&(b>=Xb&&b<Tb)}())return Yb;if(function(){return a.indexOf(Zb)!=-1||b>=Tb}())return $b;return bb};i[Ob]={gecko1_8:V,ie10:W,ie8:_b,ie9:ac,safari:bc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};WealthManager.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};WealthManager.__computePropValue=k;o.__gwt_activeModules[S].bindings=WealthManager.__getPropMap;r(O,cc);if(q()){return D(dc)}var l;try{h([Mb,Ub],ec);h([Mb,Qb],fc);h([Nb,Wb],gc);h([Nb,Ub],hc);h([Nb,Yb],ic);h([Nb,Qb],jc);h([Nb,$b],kc);h([Mb,Wb],lc);h([Mb,$b],mc);l=f[k(Kb)][k(Ob)];var m=l.indexOf(nc);if(m!=-1){g=parseInt(l.substring(m+W),Sb);l=l.substring(V,m)}}catch(a){}WealthManager.__softPermutationId=g;return D(l+oc)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(pc);b.setAttribute(qc,rc);b.setAttribute(sc,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(tc,P);c(uc);r(tc,vc)}
B();WealthManager.__moduleBase=C();t[S].moduleBase=WealthManager.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==wc||o.location.protocol==xc);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=yc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=zc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(Ac+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+Bc]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,vc);A(H);return true}
WealthManager.succeeded=WealthManager();